routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\LanguageController;
//use App\Http\Controllers\Admin\ContentController;
use  App\Http\Controllers\Admin\IndicatorController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PaymentGatewayController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Web\FrontendController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::prefix('admin')->name('admin.')->group(function(){
    Route::get('login',[AuthController::class,'getLogin'])->name('login');
    Route::post('login',[AuthController::class,'login'])->name('postLogin');

    Route::middleware('admin')->group(function(){
        Route::get('/',[DashboardController::class,'index'])->name('dashboard');
        Route::get('logout',[AuthController::class,'logout'])->name('logout');


        // MULTI LANGUAGES
        Route::resource('language',LanguageController::class);
        Route::post('language/remove', [LanguageController::class, 'destroy'])->name('remove.language');
        Route::post('language/status-update', [LanguageController::class, 'statusUpdate'])->name('update-status.language');
        Route::post('add-translate/{id}', [LanguageController::class, 'storeTranslate'])->name('translate.store');
        Route::post('update-translate/{id}', [LanguageController::class, 'updateTranslate'])->name('translate.update');
        Route::post('remove-translate', [LanguageController::class, 'removeTranslate'])->name('translate.remove');

        // INDICATORS
        Route::resource('indicator',IndicatorController::class);
        Route::get('add-content/{id}',[IndicatorController::class,'addContent'])->name('indicator.add.content');
        Route::post('store-content/{id}',[IndicatorController::class,'storeContent'])->name('indicator.store.content');
        Route::get('edit-content/{id}',[IndicatorController::class,'editContent'])->name('indicator.edit.content');
        Route::post('update-content/{id}',[IndicatorController::class,'updateContent'])->name('indicator.update.content');
        Route::post('remove-content',[IndicatorController::class,'removeContent'])->name('indicator.remove.content');

        // CATEGORIES

        Route::resource('category',CategoryController::class);
        Route::post('category/status-update', [CategoryController::class, 'statusUpdate'])->name('update-status.category');

        // PRODUCTS
        Route::resource('product',ProductController::class);

        // ORDERS
        Route::resource('order',OrderController::class);
        Route::post('order/update-status',[OrderController::class,'updateStatus'])->name('update-status.order');
        Route::get('list-product',[OrderController::class,'getListProduct'])->name('get-list-product.order');


        // PAYMENT GATEWAYS
        Route::resource('payment-gateway',PaymentGatewayController::class);
        Route::post('payment-gateway/update-status',[PaymentGatewayController::class,'updateStatus'])->name('update-status.payment');
        Route::post('remove-payment-gateway',[PaymentGatewayController::class,'remove'])->name('remove.payment');

        // USER

        Route::resource('user',UserController::class);
    });
});

Route::get('/', [FrontendController::class,'index'])->name('web.index');
Route::post('create-view',[FrontendController::class,'createView'])->name('web.create.view');
Route::get('view/{view_code}',[FrontendController::class,'view'])->name('web.view.content');

app/Models/Content.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Content extends Model
{
    use HasFactory;
    protected $fillable = [
      'indicator_code','content_number','locale','description','content','content_vip'
    ];
}

app/Http/Controllers/Admin/ContentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ContentController extends Controller
{
    //
    public function index(){
        return view('admin.content.index');
    }
}

resources/views/admin/content/add.blade.php
@extends('admin.layouts.admin')

@section('title')
    @lang('Add New Content')
@endsection

@section('breadcrumb')
    <section class="section">
        <div class="section-header justify-content-between">
            <h1>@lang('Add New Content')</h1>
            <a href="{{route('admin.indicator.edit',$indicator->id)}}" class="btn btn-primary"> <i class="fas fa-backward"></i> @lang('Back')</a>
        </div>
    </section>
@endsection
@section('content')
    <div class="row justify-content-center mt-3">
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">{{ __('Add Content Form') }}</h6>
                </div>
                <div class="card-body">
                    <form  action="{{route('admin.indicator.store.content',$indicator->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Content Number') }} <span class="text-danger">*</span> </label>
                                <input class="form-control" type="text" name="content_number" required value="{{old('content_number')}}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Description') }}</label>
                                <input class="form-control" type="text" name="description" value="{{old('description')}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label >@lang('Content')</label>
                            <textarea class="form-control" id="content" name="content">{{old('content')}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="is_vip">@lang('Is Vip Content')</label>
                            <label class="cswitch d-flex flex-column justify-content-between align-items-start">
                                <input id="is_vip" class="cswitch--input update" value="1" type="checkbox" name="is_vip"/>
                                <span class="cswitch--trigger wrapper"></span>
                            </label>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6" id="limit_words_container">

                            </div>
                        </div>
                        <div class="mt-3 text-right">
                            <button type="submit" id="submit-btn" class="btn btn-primary btn-lg">{{ __('Submit') }}</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
@endsection
@section('script')
    <script>
        "use strict"
        $('#content').summernote();
        $(document).ready(function() {
            $('#is_vip').on('change', function() {
                if ($(this).is(':checked')) {
                    $('#limit_words_container').append('<label for="limit_word">{{ __('Limit Words') }}</label><input id="limit_word" class="form-control" type="number" name="limit_words" value="{{old('limit_words')}}" required>');
                } else {
                    $('#limit_words_container').empty();
                }
            });
        });
    </script>
@endsection

resources/views/admin/content/edit.blade.php
@extends('admin.layouts.admin')

@section('title')
    @lang('Edit Content')
@endsection

@section('breadcrumb')
    <section class="section">
        <div class="section-header justify-content-between">
            <h1>@lang('Edit Content')</h1>
            <a href="{{route('admin.indicator.edit',$indicator->id)}}" class="btn btn-primary"> <i class="fas fa-backward"></i> @lang('Back')</a>
        </div>
    </section>
@endsection
@section('content')
    <div class="row justify-content-center mt-3">
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">{{ __('Add Content Form') }}</h6>
                </div>
                <div class="card-body">
                    <form  action="{{route('admin.indicator.update.content',$indicator->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Content Number') }} <span class="text-danger">*</span></label>
                                <input class="form-control" type="text" name="content_number" required value="{{$content->content_number}}" readonly>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Description') }}</label>
                                <input class="form-control" type="text" name="description" value="{{$content->description}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label >@lang('Content')</label>
                            <textarea class="form-control" id="content" name="content">{{$content->content}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="is_vip">@lang('Is Vip Content')</label>
                            <label class="cswitch d-flex flex-column justify-content-between align-items-start">
                                <input id="is_vip" class="cswitch--input update" value="1" type="checkbox" name="is_vip" @if($content->is_vip ==1 )checked @endif/>
                                <span class="cswitch--trigger wrapper"></span>
                            </label>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6" id="limit_words_container">

                            </div>
                        </div>
                        <div class="mt-3 text-right">
                            <button type="submit" id="submit-btn" class="btn btn-primary btn-lg">{{ __('Submit') }}</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
@endsection
@section('script')
    <script>
        "use strict"
        $('#content').summernote();
        $('#content_vip').summernote();
        if ($("#is_vip").is(':checked')) {
            $('#limit_words_container').append('<label for="limit_word">{{ __('Limit Words') }}</label><input id="limit_word" class="form-control" type="number" name="limit_words" value="{{$content->limit_words}}" required>');
        } else {
            $('#limit_words_container').empty();
        }
        $(document).ready(function() {
            $('#is_vip').on('change', function() {
                if ($(this).is(':checked')) {
                    $('#limit_words_container').append('<label for="limit_word">{{ __('Limit Words') }}</label><input id="limit_word" class="form-control" type="number" name="limit_words" value="{{$content->limit_words}}" required>');
                } else {
                    $('#limit_words_container').empty();
                }
            });
        });
    </script>
@endsection