routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\LanguageController;
//use App\Http\Controllers\Admin\ContentController;
use  App\Http\Controllers\Admin\IndicatorController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PaymentGatewayController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Web\FrontendController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::prefix('admin')->name('admin.')->group(function(){
    Route::get('login',[AuthController::class,'getLogin'])->name('login');
    Route::post('login',[AuthController::class,'login'])->name('postLogin');

    Route::middleware('admin')->group(function(){
        Route::get('/',[DashboardController::class,'index'])->name('dashboard');
        Route::get('logout',[AuthController::class,'logout'])->name('logout');


        // MULTI LANGUAGES
        Route::resource('language',LanguageController::class);
        Route::post('language/remove', [LanguageController::class, 'destroy'])->name('remove.language');
        Route::post('language/status-update', [LanguageController::class, 'statusUpdate'])->name('update-status.language');
        Route::post('add-translate/{id}', [LanguageController::class, 'storeTranslate'])->name('translate.store');
        Route::post('update-translate/{id}', [LanguageController::class, 'updateTranslate'])->name('translate.update');
        Route::post('remove-translate', [LanguageController::class, 'removeTranslate'])->name('translate.remove');

        // INDICATORS
        Route::resource('indicator',IndicatorController::class);
        Route::get('add-content/{id}',[IndicatorController::class,'addContent'])->name('indicator.add.content');
        Route::post('store-content/{id}',[IndicatorController::class,'storeContent'])->name('indicator.store.content');
        Route::get('edit-content/{id}',[IndicatorController::class,'editContent'])->name('indicator.edit.content');
        Route::post('update-content/{id}',[IndicatorController::class,'updateContent'])->name('indicator.update.content');
        Route::post('remove-content',[IndicatorController::class,'removeContent'])->name('indicator.remove.content');

        // CATEGORIES

        Route::resource('category',CategoryController::class);
        Route::post('category/status-update', [CategoryController::class, 'statusUpdate'])->name('update-status.category');

        // PRODUCTS
        Route::resource('product',ProductController::class);

        // ORDERS
        Route::resource('order',OrderController::class);
        Route::post('order/update-status',[OrderController::class,'updateStatus'])->name('update-status.order');
        Route::get('list-product',[OrderController::class,'getListProduct'])->name('get-list-product.order');


        // PAYMENT GATEWAYS
        Route::resource('payment-gateway',PaymentGatewayController::class);
        Route::post('payment-gateway/update-status',[PaymentGatewayController::class,'updateStatus'])->name('update-status.payment');
        Route::post('remove-payment-gateway',[PaymentGatewayController::class,'remove'])->name('remove.payment');

        // USER

        Route::resource('user',UserController::class);
    });
});

Route::get('/', [FrontendController::class,'index'])->name('web.index');
Route::post('create-view',[FrontendController::class,'createView'])->name('web.create.view');
Route::get('view/{view_code}',[FrontendController::class,'view'])->name('web.view.content');

app/Models/Indicator.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Indicator extends Model
{
    use HasFactory;
    protected $fillable = [
      'name','code'
    ];
}

app/Http/Controllers/Admin/IndicatorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Content;
use App\Models\Indicator;
use App\Models\IndicatorLanguage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Ramsey\Uuid\Uuid;

class IndicatorController extends Controller
{
    public function index(){
        $indicators = Indicator::select('indicators.*', DB::raw('
        IFNULL(
            (SELECT indicators_language.name FROM indicators_language WHERE indicators_language.indicator_code = indicators.code AND indicators_language.locale = "'.session('lang').'"),
            indicators.name
        ) AS name
    '))
            ->paginate(12);


        return view ('admin.indicator.index',compact('indicators'));
    }
    public function store(Request $request){
        $request->validate(['name'=>'required|unique:indicators,name']);
        $data = new Indicator();
        $code = Uuid::uuid4()->toString();
        $data->name = $request->name;
        $data->code = $code;
        $data->save();
        // add language
        $indicatorLang= new IndicatorLanguage();
        $indicatorLang->indicator_code = $code;
        $indicatorLang->locale = session('lang');
        $indicatorLang->name = $request->name;
        $indicatorLang->save();
        return back()->with('success','Indicator added successfully');
    }
    public function edit(Indicator $indicator){
        $indicatorLangExist = IndicatorLanguage::where('indicator_code',$indicator->code)->where('locale',session('lang'))->first();
        if (!is_null($indicatorLangExist)){
            $indicator->name = $indicatorLangExist->name;
        }
        $contents = Content::where('indicator_code',$indicator->code)->where('locale',session('lang')??'en')->latest()->get();
        return view('admin.indicator.edit',compact('indicator','contents'));
    }
    public function update(Request $request, Indicator $indicator){
        $request->validate(['name'=>'required|unique:indicators_language,name']);
        $existIndicatorLanguage = IndicatorLanguage::where('indicator_code',$indicator->code)->where('locale',session('lang'))->first();
        if (!is_null($existIndicatorLanguage)){
            $existIndicatorLanguage->name=$request->name;
            $existIndicatorLanguage->save();
        }else{
            $data = new IndicatorLanguage();
            $data->indicator_code = $indicator->code;
            $data->locale = session('lang');
            $data->name = $request->name;
            $data->save();
        }
        return back()->with('success','Indicator updated successfully');
    }
    public function destroy(Request $request,Indicator $indicator){
        $request->validate(['id' => 'required']);
        $id = $request->id;
        $content = Content::where('indicator_code',$indicator->code)->delete();
        $indicatorLang = IndicatorLanguage::where('indicator_code',$indicator->code)->delete();
        $indicator->delete();
        return back()->with('success', "Indicator has been removed");
    }
    public function addContent($id){
        $indicator = Indicator::findOrFail($id);
        return view('admin.content.add',compact('indicator'));
    }
    public function storeContent(Request $request,$id)
    {
        $request->validate([ 'content_number' => 'required']);
        $indicator = Indicator::findOrFail($id);
        $existContent = Content::where('content_number',$request->content_number)->where('indicator_code',$indicator->code)->where('locale',session('lang'))->first();
        if (!is_null($existContent)) {
            return back()->with('error', "Content of number ".$request->content_number." already exist");
        } else {
            $data = new Content();
            $data->indicator_code = $indicator->code;
            $data->content_number = $request->content_number;
            $data->locale = session('lang');
            $data->description = $request->description;
            $data->content = $request->content;
            if ($request->is_vip){
                $data->is_vip = $request->is_vip;
                $data->limit_words = $request->limit_words;
            }
            $data->save();
            return redirect(route('admin.indicator.edit',$indicator->id))->with('success', "New content has been added");
        }
    }
    public function editContent(Request $request,$id){
        $content= Content::findOrFail($id);
        $indicator = Indicator::where('code',$content->indicator_code)->first();
        return view('admin.content.edit',compact('content','indicator'));
    }
    public function updateContent(Request $request, $id){
        $indicator = Indicator::findOrFail($id);
        $content = Content::where('content_number',$request->content_number)->where('locale',session('lang'))->first();
        $content->content = $request->content;
        $content->description = $request->description;
        if ($request->is_vip){
            $content->is_vip = $request->is_vip;
            $content->limit_words = $request->limit_words;
        }else{
            $content->is_vip = 0;
            $content->limit_words = null;
        }
        $content->save();
        return redirect(route('admin.indicator.edit',$indicator->id))->with('success', 'Content updated successfully');
    }
    public function removeContent(Request $request)
    {
        $request->validate(['id' => 'required']);
        $content = Content::findOrFail($request->id)->delete();
        return back()->with('success', "Content has been removed");
    }
}

resources/views/admin/indicator/edit.blade.php
@extends('admin.layouts.admin')

@section('title')
    @lang('Edit Indicator')
@endsection

@section('breadcrumb')
    <section class="section">
        <div class="section-header justify-content-between">
            <h1>@lang('Edit Indicator')</h1>
            <a href="{{route('admin.indicator.index')}}" class="btn btn-primary"> <i class="fas fa-backward"></i> @lang('Back')</a>
        </div>
    </section>
@endsection

@section('content')

    <div class="row justify-content-center mt-3">
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">{{ __('Edit Indicator Form') }}</h6>
                </div>
                <div class="card-body">
                    <form  action="{{route('admin.indicator.update',$indicator->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Name') }}</label>
                                <input type="text" class="form-control" id="inp-name" name="name" value="{{$indicator->name}}"  placeholder="{{ __('Enter Name') }}" required>
                            </div>
                        </div>

                        <div class="mt-3 text-right">
                            <button type="submit" id="submit-btn" class="btn btn-primary btn-lg">{{ __('Submit') }}</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header justify-content-between">
                    <div class="form-group mb-0">
                        <input class="form-control search mb-1" type="text" placeholder="@lang('Search')">
                    </div>

                    <a href="{{route('admin.indicator.add.content',$indicator->id)}}"  class="btn btn-primary add"> <i class="fas fa-plus"></i> @lang('Add New Content')
                    </a>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead class="bg-primary mb-2">
                            <tr>
                                <th class="text-white">@lang('Sl')</th>
                                <th class="text-white">@lang('Content Number')</th>
                                <th class="text-white">@lang('Locale')</th>
                                <th class="text-white">@lang('Description')</th>
                                <th class="text-white">@lang('Content')</th>
                                <th class="text-white">@lang('Vip Content')</th>
                                <th class="text-white">@lang('Limit Words')</th>
                                <th class="text-right text-white">@lang('Action')</th>
                            </tr>
                            </thead>
                            <tbody class="custom-data">
                            @php
                                $i = 0;
                            @endphp
                            @forelse ($contents as $content)
                                <tr class="elements">
                                    <td data-label="@lang('Sl')">
                                        {{++$i}}
                                    </td>
                                    <td data-label="@lang('Content Number')" data-toggle="tooltip" title="{{$content->content_number}}">
                                        {{$content->content_number}}
                                    </td>
                                    <td data-label="@lang('Locale')" data-toggle="tooltip" title="{{$content->locale}}">{{$content->locale}}</td>
                                    <td data-label="@lang('Description')" data-toggle="tooltip" title="{{$content->description}}">@if($content->description) {{$content->description}}@else <span class="text-danger">@lang('Not Yet Updated')</span>@endif</td>
                                    <td data-label="@lang('Content')" data-toggle="tooltip">@if($content->content){!! Str::limit(strip_tags($content->content),60) !!}@else <span class="text-danger">@lang('Not Yet Updated')</span> @endif</td>
                                    <td data-label="@lang('Vip Content')" data-toggle="tooltip">@if($content->is_vip == 1) <i class="fa fa-check-circle text-success" aria-hidden="true"></i> @else<i class="fa fa-times-circle text-danger" aria-hidden="true"></i>@endif</td>
                                    <td data-label="@lang('Limit Words')" data-toggle="tooltip">@if($content->limit_words) {{$content->limit_words}} @else @lang('No Limit')@endif</td>
                                    <td data-label="@lang('Action')" class="text-right">
                                        <a class="btn btn-primary edit mt-2"  href="{{route('admin.indicator.edit.content',$content->id)}}"><i class="fas fa-edit"></i></a>

                                        <a class="btn btn-danger remove mt-2" data-key="{{$content->id}}" data-route="{{route('admin.indicator.remove.content')}}" href="javascript:void(0)"><i class="fas fa-trash"></i></a>
                                    </td>
                                </tr>
                            @empty

                                <tr>
                                    <td class="text-center" colspan="100%">@lang('No Data Found')</td>
                                </tr>

                            @endforelse

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="remove" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="{{route('admin.indicator.remove.content')}}" method="post">
                @csrf
                <div class="modal-content">
                    <div class="modal-body">
                        <h5 class="mt-3">@lang('Are you sure to remove?')</h5>
                        <input type="hidden" name="id" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-dark" data-dismiss="modal">@lang('Close')</button>
                        <button type="submit" class="btn btn-danger">@lang('Confirm')</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script>
        'use strict';
        var elements = $('.elements');
        $(document).on('input','.search',function(){
            var search = $(this).val().toUpperCase();
            var match = elements.filter(function (idx, elem) {
                return $(elem).text().trim().toUpperCase().indexOf(search) >= 0 ? elem : null;
            }).sort();
            var content = $('.custom-data');
            if (match.length == 0) {
                content.html('<tr><td colspan="100%" class="text-center">@lang('Data Not Found')</td></tr>');
            }else{
                content.html(match);
            }
        });


        $(document).on('click','.remove',function () {
            const modal = $('#remove')
            modal.find('input[name=id]').val($(this).data('key'))
            modal.modal('show')
        })
        $('.add').on('click',function () {
            $('#translate').find('form')[0].reset();
            $('#translate').find('.modal-title').text('@lang('Add New Content')')
        })
    </script>
@endsection

resources/views/admin/indicator/index.blade.php
@extends('admin.layouts.admin')

@section('title')
    @lang('Manage Indicators')
@endsection

@section('breadcrumb')
    <section class="section">
        <div class="section-header justify-content-between">
            <h1>@lang('Manage Indicators')</h1>
            <button class="btn btn-primary bg-primary" data-toggle="modal" data-target="#modelId"> <i class="fas fa-plus"></i> @lang('Add New Indicator')</button>
        </div>
    </section>
@endsection


@section('content')

    <div class="row">
        @forelse ($indicators as $indicator)
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 currency--card">
                <div class="card card-primary">
                    <div class="card-header d-flex justify-content-between">
                        <h4><i class="fas fa-language"></i> {{$indicator->name}}</h4>
{{--                            <a href="javascript:void(0)" class="btn btn-danger btn-sm remove" data-id="{{$indicator->id}}"><i class="fas fa-trash-alt"></i></a>--}}
                    </div>
                    <div class="card-body">
                        <ul class="list-group mb-3">
                            <li class="list-group-item d-flex justify-content-between">
                                <p>@lang('Code') :<span class="font-weight-bold">{{$indicator->code}}</span></p>
                            </li>
                        </ul>

                        <a href="{{route('admin.indicator.edit',$indicator->id)}}" class="btn btn-primary btn-block"><i class="fas fa-edit"></i> @lang('Edit Indicator')</a>

                    </div>
                </div>
            </div>
        @empty
            <div class="w-100 text-center">
                <p>@lang('No Data Found')</p>
            </div>
        @endforelse
    </div>

    @if ($indicators->hasPages())
        {{ $indicators->links('admin.partials.paginate') }}
    @endif

    <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="{{route('admin.indicator.store')}}" method="POST">
                @csrf
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">@lang('Add New Indicator')</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label>@lang('Indicator Name')</label>
                            <input class="form-control" type="text" name="name" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-dark" data-dismiss="modal">@lang('Close')</button>
                        <button type="submit" class="btn btn-primary">@lang('Save')</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal fade" id="removeModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="{{route('admin.indicator.destroy',$indicator->id)}}" method="POST">
                @method("delete")
                @csrf
                <input type="hidden" name="id">
                <div class="modal-content">
                    <div class="modal-body">
                        <h5 class="mt-3">@lang('Are you sure to remove?')</h5>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-dark" data-dismiss="modal">@lang('Close')</button>
                        <button type="submit" class="btn btn-danger">@lang('Confirm')</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $('.remove').on('click',function () {
            $('#removeModal').find('input[name=id]').val($(this).data('id'))
            $('#removeModal').modal('show')
        })
    </script>
@endsection