routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\LanguageController;
//use App\Http\Controllers\Admin\ContentController;
use  App\Http\Controllers\Admin\IndicatorController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PaymentGatewayController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Web\FrontendController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::prefix('admin')->name('admin.')->group(function(){
    Route::get('login',[AuthController::class,'getLogin'])->name('login');
    Route::post('login',[AuthController::class,'login'])->name('postLogin');

    Route::middleware('admin')->group(function(){
        Route::get('/',[DashboardController::class,'index'])->name('dashboard');
        Route::get('logout',[AuthController::class,'logout'])->name('logout');


        // MULTI LANGUAGES
        Route::resource('language',LanguageController::class);
        Route::post('language/remove', [LanguageController::class, 'destroy'])->name('remove.language');
        Route::post('language/status-update', [LanguageController::class, 'statusUpdate'])->name('update-status.language');
        Route::post('add-translate/{id}', [LanguageController::class, 'storeTranslate'])->name('translate.store');
        Route::post('update-translate/{id}', [LanguageController::class, 'updateTranslate'])->name('translate.update');
        Route::post('remove-translate', [LanguageController::class, 'removeTranslate'])->name('translate.remove');

        // INDICATORS
        Route::resource('indicator',IndicatorController::class);
        Route::get('add-content/{id}',[IndicatorController::class,'addContent'])->name('indicator.add.content');
        Route::post('store-content/{id}',[IndicatorController::class,'storeContent'])->name('indicator.store.content');
        Route::get('edit-content/{id}',[IndicatorController::class,'editContent'])->name('indicator.edit.content');
        Route::post('update-content/{id}',[IndicatorController::class,'updateContent'])->name('indicator.update.content');
        Route::post('remove-content',[IndicatorController::class,'removeContent'])->name('indicator.remove.content');

        // CATEGORIES

        Route::resource('category',CategoryController::class);
        Route::post('category/status-update', [CategoryController::class, 'statusUpdate'])->name('update-status.category');

        // PRODUCTS
        Route::resource('product',ProductController::class);

        // ORDERS
        Route::resource('order',OrderController::class);
        Route::post('order/update-status',[OrderController::class,'updateStatus'])->name('update-status.order');
        Route::get('list-product',[OrderController::class,'getListProduct'])->name('get-list-product.order');


        // PAYMENT GATEWAYS
        Route::resource('payment-gateway',PaymentGatewayController::class);
        Route::post('payment-gateway/update-status',[PaymentGatewayController::class,'updateStatus'])->name('update-status.payment');
        Route::post('remove-payment-gateway',[PaymentGatewayController::class,'remove'])->name('remove.payment');

        // USER

        Route::resource('user',UserController::class);
    });
});

Route::get('/', [FrontendController::class,'index'])->name('web.index');
Route::post('create-view',[FrontendController::class,'createView'])->name('web.create.view');
Route::get('view/{view_code}',[FrontendController::class,'view'])->name('web.view.content');

resources/views/admin/partials/paginate.blade.php
<nav class="d-inline-block ml-4">
    <ul class="pagination flex-wrap">
        @if($paginator->onFirstPage())

        @else
            <li class="page-item">
                <a class="page-link" href="{{$paginator->previousPageUrl()}}" tabindex="-1">
                    <i class="fas fa-chevron-left"></i>
                </a>
            </li>
        @endif

        @foreach ($elements as $element)

            @if (is_array($element) && count($element) < 2)


            @else
                @if (is_array($element))

                    @foreach ($element as $key=> $el)

                        <li class="page-item {{ $key == $paginator->currentPage() ? 'active' : '' }}">
                            <a class="page-link" href="{{ $el }}">{{$key}}</a>
                        </li>

                    @endforeach
                @else
                    <li class="page-item {{ $key == $paginator->currentPage() ? 'active' : '' }}">
                        <a class="page-link" href="javascript:;">...</a>
                    </li>
                @endif
            @endif
        @endforeach

        @if($paginator->hasMorePages())
            <li class="page-item">
                <a class="page-link" href="{{$paginator->nextPageUrl()}}">
                    <i class="fas fa-chevron-right"></i>
                </a>
            </li>
        @endif
    </ul>
</nav>

resources/views/admin/partials/sidebar.blade.php
<aside id="sidebar-wrapper">

    <ul class="sidebar-menu mb-5">
        <li class="menu-header text-center mb-5 mt-2"><img class="w-50" src="{{getPhoto('logo.png')}}" alt=""></li>
        <li class="menu-header">@lang('Dashboard')</li>
        <li class="nav-item {{menu('admin.dashboard')}}"><a href="{{route('admin.dashboard')}}" class="nav-link"><i class="fas fa-fire"></i><span>@lang('Dashboard')</span></a></li>
        <li class="menu-header">@lang('Manage Users')</li>
        <li class="nav-item {{menu(['admin.user*'])}}">
            <a href="{{route('admin.user.index')}}" class="nav-link"><i class="fas fa-user"></i> <span>@lang('Manage Users')</span></a>
        </li>
        <li class="menu-header">@lang('Manage Language')</li>
        <li class="nav-item {{menu(['admin.language*'])}}">
            <a href="{{route('admin.language.index')}}" class="nav-link"><i class="fas fa-language"></i> <span>@lang('Manage Language')</span></a>
        </li>
        <li class="menu-header">@lang('Manage Indicators')</li>
        <li class="nav-item {{menu(['admin.indicator*'])}}">
            <a href="{{route('admin.indicator.index')}}" class="nav-link"><i class="fas fa-newspaper"></i> <span>@lang('Manage Indicators')</span></a>
        </li>
        <li class="menu-header">@lang('Manage Categories')</li>
        <li class="nav-item {{menu(['admin.category*'])}}">
            <a href="{{route('admin.category.index')}}" class="nav-link"><i class="fas fa-th-list"></i> <span>@lang('Manage Categories')</span></a>
        </li>
        <li class="menu-header">@lang('Manage Products')</li>
        <li class="nav-item {{menu(['admin.product*'])}}">
            <a href="{{route('admin.product.index')}}" class="nav-link"><i class="fas fa-tags"></i> <span>@lang('Manage Products')</span></a>
        </li>
        <li class="menu-header">@lang('Manage Orders')</li>
        <li class="nav-item {{menu(['admin.order*'])}}">
            <a href="{{route('admin.order.index')}}" class="nav-link"><i class="fas fa-shopping-cart"></i> <span>@lang('Manage Orders')</span></a>
        </li>
        <li class="menu-header">@lang('Payment Gateways')</li>
        <li class="nav-item {{menu(['admin.payment-gateway*'])}}">
            <a href="{{route('admin.payment-gateway.index')}}" class="nav-link"><i class="fas fa-money-check-alt"></i> <span>@lang('Payment Gateways')</span></a>
        </li>
{{--        <li class="menu-header">@lang('Contacts')</li>--}}
{{--        <li class="nav-item {{menu('admin.contact')}}">--}}
{{--            <a href="{{route('admin.contact')}}" class="nav-link"><i--}}
{{--                    class="fas fa-file-contract"></i><span>@lang('Contacts')</span></a>--}}
{{--        </li>--}}
{{--        <li class="nav-item {{menu('admin.news.list')}}">--}}
{{--            <a href="{{route('admin.news.list')}}" class="nav-link"><i--}}
{{--                    class="fas fa-newspaper"></i><span>@lang('News')</span></a>--}}
{{--        </li>--}}
    </ul>
</aside>

resources/views/admin/partials/topbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">

    <ul class="navbar-nav mr-auto icon-menu">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg text-white"><i class="fas fa-bars"></i></a></li>
    </ul>

    <ul class="navbar-nav navbar-right">
        <li class="dropdown">
            @php
            $languages = getLanguage();
            @endphp
            <select class="selectpicker" data-size="auto" data-fit="10">
                @foreach($languages as $language)
                    <option value="{{$language->id}}" @if(session('lang')== $language->code) selected @endif>@lang($language->language)</option>
                @endforeach
            </select>
        </li>
        <li class="text-white">
            <a href="" class="nav-link nav-link-lg text-white"><i class="fas fa-home pr-1"></i></a>
        </li>
        <li class="dropdown"><a href="" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user text-white">
                <img alt="image" src="{{getPhoto(admin()->photo)}}" class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">{{admin()->email}}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> @lang('Profile Setting')
                </a>
                <a href="" class="dropdown-item has-icon">
                    <i class="fas fa-key"></i> @lang('Change Password')
                </a>

                <div class="dropdown-divider"></div>
                <a href="{{route('admin.logout')}}" class="dropdown-item has-icon text-danger">
                    <i class="fas fa-sign-out-alt"></i> @lang('Logout')
                </a>
            </div>
        </li>
    </ul>
</nav>