routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\LanguageController;
//use App\Http\Controllers\Admin\ContentController;
use  App\Http\Controllers\Admin\IndicatorController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PaymentGatewayController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Web\FrontendController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::prefix('admin')->name('admin.')->group(function(){
    Route::get('login',[AuthController::class,'getLogin'])->name('login');
    Route::post('login',[AuthController::class,'login'])->name('postLogin');

    Route::middleware('admin')->group(function(){
        Route::get('/',[DashboardController::class,'index'])->name('dashboard');
        Route::get('logout',[AuthController::class,'logout'])->name('logout');


        // MULTI LANGUAGES
        Route::resource('language',LanguageController::class);
        Route::post('language/remove', [LanguageController::class, 'destroy'])->name('remove.language');
        Route::post('language/status-update', [LanguageController::class, 'statusUpdate'])->name('update-status.language');
        Route::post('add-translate/{id}', [LanguageController::class, 'storeTranslate'])->name('translate.store');
        Route::post('update-translate/{id}', [LanguageController::class, 'updateTranslate'])->name('translate.update');
        Route::post('remove-translate', [LanguageController::class, 'removeTranslate'])->name('translate.remove');

        // INDICATORS
        Route::resource('indicator',IndicatorController::class);
        Route::get('add-content/{id}',[IndicatorController::class,'addContent'])->name('indicator.add.content');
        Route::post('store-content/{id}',[IndicatorController::class,'storeContent'])->name('indicator.store.content');
        Route::get('edit-content/{id}',[IndicatorController::class,'editContent'])->name('indicator.edit.content');
        Route::post('update-content/{id}',[IndicatorController::class,'updateContent'])->name('indicator.update.content');
        Route::post('remove-content',[IndicatorController::class,'removeContent'])->name('indicator.remove.content');

        // CATEGORIES

        Route::resource('category',CategoryController::class);
        Route::post('category/status-update', [CategoryController::class, 'statusUpdate'])->name('update-status.category');

        // PRODUCTS
        Route::resource('product',ProductController::class);

        // ORDERS
        Route::resource('order',OrderController::class);
        Route::post('order/update-status',[OrderController::class,'updateStatus'])->name('update-status.order');
        Route::get('list-product',[OrderController::class,'getListProduct'])->name('get-list-product.order');


        // PAYMENT GATEWAYS
        Route::resource('payment-gateway',PaymentGatewayController::class);
        Route::post('payment-gateway/update-status',[PaymentGatewayController::class,'updateStatus'])->name('update-status.payment');
        Route::post('remove-payment-gateway',[PaymentGatewayController::class,'remove'])->name('remove.payment');

        // USER

        Route::resource('user',UserController::class);
    });
});

Route::get('/', [FrontendController::class,'index'])->name('web.index');
Route::post('create-view',[FrontendController::class,'createView'])->name('web.create.view');
Route::get('view/{view_code}',[FrontendController::class,'view'])->name('web.view.content');

resources/views/admin/payment/add.blade.php
@extends('admin.layouts.admin')

@section('title')
    @lang('Add Payment Gateway')
@endsection

@section('breadcrumb')
    <section class="section">
        <div class="section-header justify-content-between">
            <h1>@lang('Add Payment Gateway')</h1>
            <a href="{{route('admin.payment-gateway.index')}}" class="btn btn-primary"> <i class="fas fa-backward"></i> @lang('Back')</a>
        </div>
    </section>
@endsection
@section('content')
    <div class="row justify-content-center mt-3">
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">{{ __('Add Payment GateWay Form') }}</h6>
                </div>
                <div class="card-body">
                    <form  action="{{route('admin.payment-gateway.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Title') }} <span class="text-danger">*</span> </label>
                                <input class="form-control" type="text" name="title" required value="{{old('title')}}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Name') }} <span class="text-danger">*</span> </label>
                                <input class="form-control" type="text" name="name" required value="{{old('name')}}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Detail') }}</label>
                                <textarea class="form-control" id="detail" name="detail">{{old('detail')}}</textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label for="inp-name">{{ __('Settings') }}</label>
                                <button class="btn btn-primary d-block mb-5" id="add-row" type="button">@lang('Add Config')</button>
                                <div id="key-value-container">
                                    <div class="key-value-row row mb-3">
                                        <div class="col-md-6">
                                            <label for="">@lang('Key')</label>
                                        <input class="form-control" type="text" name="keys[]">
                                        </div>
                                        <div class="col-md-5">
                                            <label for="">@lang('Value')</label>
                                            <input class="form-control" type="text" name="values[]">
                                        </div>
                                        <div class="col-md-1 d-flex align-items-end">
                                            <button class="btn btn-danger remove-row" type="button"><i class="fas fa-trash-alt"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="active">@lang('Active')</label>
                            <label class="cswitch d-flex flex-column justify-content-between align-items-start">
                                <input id="active" class="cswitch--input update" value="1" type="checkbox" name="active" checked/>
                                <span class="cswitch--trigger wrapper"></span>
                            </label>
                        </div>
                        <div class="mt-3 text-right">
                            <button type="submit" id="submit-btn" class="btn btn-primary btn-lg">{{ __('Submit') }}</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
@endsection
@section('script')
    <script>
        "use strict"
        $(document).ready(function() {
            $('#add-row').click(function() {
                var container = $('#key-value-container');
                var row = $('<div>').addClass('key-value-row row mb-3');
                row.html('<div class="col-md-6"><label for="">@lang('Key')</label>'+'<input class="form-control" type="text" name="keys[]">'+'</div>' +
                    '<div class="col-md-5"><label for="">@lang('Value')</label>'+'<input class="form-control" type="text" name="values[]">'+'</div>' +'<div class="col-md-1 d-flex align-items-end">' +
                '<button class="btn btn-danger remove-row" type="button"><i class="fas fa-trash-alt"></i></button>' +
                '</div>');
                container.append(row);
            });
        });
        $(document).on('click', '.remove-row', function() {
            $(this).closest('.key-value-row').remove();
        });
    </script>
@endsection

resources/views/admin/payment/edit.blade.php
@extends('admin.layouts.admin')

@section('title')
    @lang('Edit Payment Gateway')
@endsection

@section('breadcrumb')
    <section class="section">
        <div class="section-header justify-content-between">
            <h1>@lang('Edit Payment Gateway')</h1>
            <a href="{{route('admin.payment-gateway.index')}}" class="btn btn-primary"> <i class="fas fa-backward"></i> @lang('Back')</a>
        </div>
    </section>
@endsection
@section('content')
    <div class="row justify-content-center mt-3">
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">{{ __('Edit Payment GateWay Form') }}</h6>
                </div>
                <div class="card-body">
                    <form  action="{{route('admin.payment-gateway.update',$paymentGateway->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Title') }} <span class="text-danger">*</span> </label>
                                <input class="form-control" type="text" name="title" required value="{{$paymentGateway->title}}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Name') }} <span class="text-danger">*</span> </label>
                                <input class="form-control" type="text" name="name" required value="{{$paymentGateway->name}}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="inp-name">{{ __('Detail') }}</label>
                                <textarea class="form-control" id="detail" name="detail">{{$paymentGateway->detail}}</textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label for="inp-name">{{ __('Settings') }}</label>
                                <button class="btn btn-primary d-block mb-5" id="add-row" type="button">@lang('Add Config')</button>
                                <div id="key-value-container">
                                    @foreach (json_decode($paymentGateway->settings, true) as $key => $value)
                                    <div class="key-value-row row mb-3">
                                        <div class="col-md-6">
                                            <label for="">@lang('Key')</label>
                                            <input class="form-control" type="text" name="keys[]" value="{{$key}}">
                                        </div>
                                        <div class="col-md-5">
                                            <label for="">@lang('Value')</label>
                                            <input class="form-control" type="text" name="values[]" value="{{$value}}">
                                        </div>
                                        <div class="col-md-1 d-flex align-items-end">
                                            <button class="btn btn-danger remove-row" type="button"><i class="fas fa-trash-alt"></i></button>
                                        </div>
                                    </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="active">@lang('Active')</label>
                            <label class="cswitch d-flex flex-column justify-content-between align-items-start">
                                <input id="active" class="cswitch--input update" value="1" type="checkbox" name="active" {{$paymentGateway->active == 1 ? 'checked' : ''}}/>
                                <span class="cswitch--trigger wrapper"></span>
                            </label>
                        </div>
                        <div class="mt-3 text-right">
                            <button type="submit" id="submit-btn" class="btn btn-primary btn-lg">{{ __('Submit') }}</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
@endsection
@section('script')
    <script>
        $(document).ready(function() {
            $('#add-row').click(function() {
                var container = $('#key-value-container');
                var row = $('<div>').addClass('key-value-row row mb-3');
                row.html('<div class="col-md-6"><label for="">@lang('Key')</label>'+'<input class="form-control" type="text" name="keys[]">'+'</div>' +
                    '<div class="col-md-5"><label for="">@lang('Value')</label>'+'<input class="form-control" type="text" name="values[]">'+'</div>' +'<div class="col-md-1 d-flex align-items-end">' +
                    '<button class="btn btn-danger remove-row" type="button"><i class="fas fa-trash-alt"></i></button>' +
                    '</div>');
                container.append(row);
            });
        });
        $(document).on('click', '.remove-row', function() {
            $(this).closest('.key-value-row').remove();
        });
    </script>
@endsection

resources/views/admin/payment/index.blade.php
@extends('admin.layouts.admin')

@section('title')
    @lang('Manage Payment Gateways')
@endsection

@section('breadcrumb')
    <section class="section">
        <div class="section-header justify-content-between">
            <h1>@lang('Manage Payment Gateways')</h1>
            <a href="{{route('admin.payment-gateway.create')}}"  class="btn btn-primary add"> <i class="fas fa-plus"></i> @lang('Add New Payment Gateway')</a>
        </div>
    </section>
@endsection
@section('content')
    <div class="row">
        @foreach ($paymentGateways as $paymentGateway)
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 currency--card">
                <div class="card card-primary">
                    <div class="card-header d-flex justify-content-between">
                        <h4><i class="fas fa-credit-card"></i> @lang($paymentGateway->title)</h4>
                            <a href="javascript:void(0)" class="btn btn-danger btn-sm remove" data-id="{{$paymentGateway->id}}"><i class="fas fa-trash-alt"></i></a>
                    </div>
                    <div class="card-body">
                        <ul class="list-group mb-3">
                            <li class="list-group-item d-flex justify-content-between">@lang('Name') :
                                <span class="font-weight-bold">{{$paymentGateway->name}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between">@lang('Active') :
                                <label class="cswitch d-flex justify-content-between align-items-center">
                                    <input class="cswitch--input update" value="{{$paymentGateway->id}}" type="checkbox" {{$paymentGateway->active == 1 ? 'checked' : ''}} />
                                    <span class="cswitch--trigger wrapper"></span>
                                </label>
                            </li>
                        </ul>

                        <a href="{{route('admin.payment-gateway.edit',$paymentGateway->id)}}" class="btn btn-primary btn-block"><i class="fas fa-edit"></i> @lang('Edit Payment Gateway')</a>

                    </div>
                </div>
            </div>
        @endforeach
    </div>

    @if ($paymentGateways->hasPages())
        {{ $paymentGateways->links('admin.partials.paginate') }}
    @endif
    <div class="modal fade" id="removeModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="{{route('admin.remove.payment')}}" method="POST">
                @csrf
                <input type="hidden" name="id">
                <div class="modal-content">
                    <div class="modal-body">
                        <h5 class="mt-3">@lang('Are you sure to remove?')</h5>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-dark" data-dismiss="modal">@lang('Close')</button>
                        <button type="submit" class="btn btn-danger">@lang('Confirm')</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('script')
    <script>
        $('.update').on('change', function () {
            var url = "{{route('admin.update-status.payment')}}"
            var val = $(this).val()
            var data = {
                id:val,
                _token:"{{csrf_token()}}"
            }
            $.post(url,data,function(response) {
                if(response.error){
                    toast('error',response.error)
                    return false;
                }
                toast('success',response.success)
                setTimeout(function () {
                    location.reload(); // Reload trang sau 300ms
                }, 300);
            })
        });
        $('.remove').on('click',function () {
            $('#removeModal').find('input[name=id]').val($(this).data('id'))
            $('#removeModal').modal('show')
        })
    </script>
@endsection